name: "Node-to-docker"
on:
  workflow_dispatch:

jobs:
  node-build-push-docker:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
          token: ${{ secrets.REPO_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: onfinality
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      ## node
      - name: Get updated node version
        id: get-node-version
        run: |
          sh .github/workflows/scripts/nodeVersion.sh

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./packages/node/Dockerfile
          tags: onfinality/subql-node:v${{ steps.get-node-version.outputs.NODE_VERSION }},onfinality/subql-node:latest
          build-args: RELEASE_VERSION=${{ steps.get-node-version.outputs.NODE_VERSION }}

      - name: Image digest
        if: steps.changed-node.outputs.changed == 'true'
        run: echo ${{ steps.docker_build.outputs.digest }}

