name: "Release"
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'

jobs:

  Release-Publish:
    name: Bump-Release-Publish
    if: "!startsWith(github.event.head_commit.message, '[SKIP CI]') && startsWith(github.event.head_commit.message, '[release]') && github.repository == 'OnFinality-io/subql'"
    runs-on: ubuntu-latest
    needs: setups
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'

      - uses: marceloprado/has-changed-path@v1
        id: changed-common
        with:
          paths: packages/common

      - uses: marceloprado/has-changed-path@v1
        id: changed-cli
        with:
          paths: packages/cli

      - uses: marceloprado/has-changed-path@v1
        id: changed-types
        with:
          paths: packages/types

      - run: yarn

      - name: Publish Common
        if: steps.changed-common.outputs.changed == 'true'
        working-directory: packages/common
        run: echo "Changes exist in common" && yarn build && yarn npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish Cli
        if: steps.changed-cli.outputs.changed == 'true'
        working-directory: packages/cli
        run: echo "Changes exist in cli" && yarn build && yarn npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}


      - name: Publish Types
        if: steps.changed-types.outputs.changed == 'true'
        working-directory: packages/types
        run: echo "Changes exist in types" && yarn build && yarn npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}


      - name: Commit changes
        uses: EndBug/add-and-commit@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
