name: "Release"
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'

jobs:

  Build-Publish:
    name: Build-Publish
    if: "!startsWith(github.event.head_commit.message, '[SKIP CI]') && startsWith(github.event.head_commit.message, '[release]') && github.repository == 'OnFinality-io/subql'"
    runs-on: ubuntu-latest
    steps:
      #Check out
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'

    #Identify changes
      - uses: marceloprado/has-changed-path@v1
        id: changed-common
        with:
          paths: packages/common

      - uses: marceloprado/has-changed-path@v1
        id: changed-cli
        with:
          paths: packages/cli

      - uses: marceloprado/has-changed-path@v1
        id: changed-types
        with:
          paths: packages/types

      - uses: marceloprado/has-changed-path@v1
        id: changed-node
        with:
          paths: packages/node

      #Get node version
      - name: Get updated node version
        id: get-node-version
        run: |
          sh .github/workflows/scripts/nodeVersion.sh

      - run: yarn

      #Publish to npm

      - name: Publish Common
        if: steps.changed-common.outputs.changed == 'true'
        working-directory: packages/common
        run: echo "Changes exist in common" && yarn build && yarn npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish Cli
        if: steps.changed-cli.outputs.changed == 'true'
        working-directory: packages/cli
        run: echo "Changes exist in cli" && yarn build && yarn npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish Types
        if: steps.changed-types.outputs.changed == 'true'
        working-directory: packages/types
        run: echo "Changes exist in types" && yarn build && yarn npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      #Publish node docker image
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        if: steps.changed-node.outputs.changed == 'true'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        if: steps.changed-node.outputs.changed == 'true'

      - name: Login to DockerHub
        uses: docker/login-action@v1
        if: steps.changed-node.outputs.changed == 'true'
        with:
          username: onfinality
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        if: steps.changed-node.outputs.changed == 'true'
        with:
          push: true
          tags: onfinality/subql-node:v${{ steps.get-node-version.outputs.NODE_VERSION }}

      - name: Image digest
        if: steps.changed-node.outputs.changed == 'true'
        run: echo ${{ steps.docker_build.outputs.digest }}
